### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Ellmen** [Ellmen/pharmokinetics#20]
This is a big issue and should probably be split into multiple issues for the different classes/methods.

**Comment by Ramanspec** [comment]
Ideas so far:

1. sum of the mass of the drug in all comparments <= total administered dose at that point in time
2. the mass in each individual compartment >=0 , < infinity
3. volume of each compartment >=0, <inifinity
4. absolute value (change in mass in the central compartment ) >= absolute value (change of mass in dosing compartment + change of mass of all peripheral compartments)

**Comment by Ramanspec** [comment]
These are all sound tests, but they require significant more work that we feel is beyond the scope of this project, especially given that our current code coverage is already 100%. Optional for future extension of the project.
